//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public int id_vehiculo { get; set; }
        public int id_tipovehiculo { get; set; }
        public int id_marca { get; set; }
        public int id_empleado { get; set; }
        public string color { get; set; }
        public string num_placa { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual marca marca { get; set; }
        public virtual tipo_vehiculo tipo_vehiculo { get; set; }
    }
}
